public enum CardEffectType
{
    None,
    DamageEnemyHeadquarters,
    DamageTargetUnit,
    DamageTargetUnitAndAdjacent,
    RepairHeadquarters,
    DrawCards,
    BuffFriendlyUnit,
    PinTargetUnit,
    CancelAttack,
    AddUnitToHand,
    DeployWithBlitz,
    IncreaseEnemyCosts,
    GrantFriendlyDefense,
    DrawForCardsPlayed,
    Trap,
    FieldIntel
}
